routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PostsController@index')->name('index');
Route::get('manifest.json', 'PagesController@manifest');
Route::get('sitemap.xml', 'PagesController@sitemap')->name('sitemap');
Route::get('feed', 'PagesController@feed')->name('feed');

Route::get('/tag/{tag}', 'TagsController@show')->name('tag.show');
Route::get('/tags', 'TagsController@index')->name('tags');
Route::resource('category', 'CategoriesController');
Route::patch('/post/restore', 'PostsController@restore')->name('post.restore');
Route::post('/post/{post}/unlock', 'PostsController@unlock')->name('post.unlock');
Route::resource('post', 'PostsController');
Route::resource('comment', 'CommentsController', ['only' => ['store', 'destroy']])->middleware('auth');
Route::post('/favorites/comment/{comment}', 'FavoritesController@comment');
Route::post('/favorites/post/{post}', 'FavoritesController@post');
Route::post('/subscribe', 'SubscribesController@store');
Route::get('/search/{keyword}', 'PostsController@search')->name('post.search');

Route::get('upload', 'FilesController@index')->name('upload.index');
Route::post('upload', 'FilesController@store')->name('upload.store');
Route::delete('upload', 'FilesController@destroy')->name('upload.destroy');

Auth::routes(['verify' => true]);
Route::resource('notifications', 'NotificationsController', ['only' => ['index']]);
Route::post('/at', 'UsersController@index');
Route::get('/user/{user}', 'UsersController@show')->name('user.show');
Route::get('/user/{user}/edit', 'UsersController@edit')->name('user.edit');
Route::put('/user/{user}/edit', 'UsersController@update')->name('user.update');
Route::match(['get', 'put'], '/user/{user}/avatar', 'UsersController@avatar')->name('user.avatar');
Route::match(['get', 'put'], '/user/{user}/password', 'UsersController@password')->name('user.password');
Route::match(['get', 'put'], '/user/{user}/binding', 'UsersController@binding')->name('user.binding');
Route::match(['get', 'put'], '/user/{user}/paycode', 'UsersController@paycode')->name('user.paycode');

Route::resource('link', 'LinksController');
Route::get('setting', 'SettingsController@index')->name('setting.index');
Route::put('setting', 'SettingsController@update')->name('setting.update');
Route::get('/posts', 'PostsController@list')->name('post.manage');
Route::get('clear', 'SettingsController@clear')->name('setting.clear');

Route::post('pay/alipay/create', 'Pay\AlipayController@create');
Route::get('pay/alipay/return', 'Pay\AlipayController@return');
Route::post('pay/alipay/notify', 'Pay\AlipayController@notify');
Route::get('pay/alipay/{order}', 'Pay\AlipayController@pay');
Route::post('pay/wechat/pay', 'Pay\WechatController@pay');
Route::post('pay/wechat/notify', 'Pay\WechatController@notify');

app/Http/Controllers/Api/PostsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cache;

class PostsController extends Controller
{
    public function recent(Request $request)
    {
        $count = $request->input('count', 5);
        $recent_posts = Cache::remember('recent:posts', 3600, function () use ($count) {
            return Post::getTopBy('id', $count);
        });
        return $recent_posts;
    }

    public function hot(Request $request)
    {
        $count = $request->input('count', 3);
        $hot_posts = Cache::remember('hot:posts', 3600, function () use ($count) {
            return Post::getTopBy('view_count', $count);
        });
        return $hot_posts;
    }

    public function search(Request $request)
    {
        $page = $request->input('page', 1);
        $keyword = $request->keyword;
        $posts = Cache::remember('search:' . $keyword . ':' . $page, 3600, function () use ($keyword) {
            $lists = Post::search($keyword)->orderBy('id', 'desc')->paginate(12);
            $lists->load('user', 'tags');
            return $lists;
        });
        return compact('posts', 'keyword');
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $page = $request->input('page', 1);
        $posts = Cache::tags(['index-post'])->rememberForever('post:list:' . $page, function () {
            return Post::gettype('published')->orderBy('id', 'desc')->with(['user:id,name', 'tags'])->paginate(12);
        });
        return $posts;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param Post $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $data = Cache::rememberForever('post:' . $post->id, function () use ($post) {
            $data = $post->load('user', 'tags', 'comments');
            $data->comments->load('user');
            return $data;
        });
        $post->visits()->increment();
        return $data;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Events\PostChange;
use App\Http\Requests\PostRequest;
use App\Models\Tag;
use App\Services\Upload;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Models\Post;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;

class PostsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show', 'search', 'unlock']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (!alreadyInstalled()) {
            return redirect()->route('LaravelInstaller::welcome');
        }
        $page = $request->input('page', 1);
        $posts = Cache::tags(['index-post'])->rememberForever('post:list:' . $page, function () {
            return Post::gettype('published')->orderBy('id', 'desc')->with(['user', 'tags'])
                ->withCount(['comments', 'favorites'])->paginate(12);
        });
        return view('pages.index', compact('posts'));
    }

    /**
     * 文章管理
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function list(Request $request)
    {
        $type = $request->input('type', 'all');
        switch ($type) {
            case 'all':
                $posts = Post::orderBy('id', 'desc')->paginate(12);
                break;
            case 'published':
                $posts = Post::gettype('published')->orderBy('id', 'desc')->paginate(12);
                break;
            case 'draft':
                $posts = Post::gettype('draft')->orderBy('id', 'desc')->paginate(12);
                break;
            case 'recycle':
                $posts = Post::onlyTrashed()->orderBy('id', 'desc')->paginate(12);
                break;
        }
        return view('posts.index', compact('posts', 'type'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        try {
            $this->authorize('create', Post::class);
            $tags = Tag::all()->pluck('name')->toJson(JSON_UNESCAPED_UNICODE);
            return view('posts.create', compact('tags'));
        } catch (\Exception $exception) {
            return redirect()->back()->with('danger', '管理员未开放普通用户发表文章功能！');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PostRequest $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function store(PostRequest $request)
    {
        $this->authorize('create', Post::class);
        //封面图处理
        $cover_path = '';
        if ($request->hasFile('cover')) {
            $result = Upload::file($request->file('cover'), 'cover');
            Upload::reduceSize($result['path'], 1024, null, true);
            if ($result) {
                $cover_path = $result['path'];
            }
        }

        if ($request->input('publish_time')) {
            $publish_time = strtotime($request->input('publish_time'));
        } else {
            $publish_time = 0;
        }

        //保存文章
        $post = Post::create([
            'title' => $request->input('title'),
            'keyword' => str_replace(' ', '', $request->input('tags')),
            'user_id' => Auth::id(),
            'content' => $request->input('content'),
            'description' => $request->input('description'),
            'cover' => $cover_path,
            'publish_time' => $publish_time,
            'password' => $request->input('password'),
            'allow_comment' => $request->input('allow_comment'),
            'status' => $request->input('status'),
            'category_id' => $request->input('category_id')
        ]);
        $post->save();
        //标签关联
        $tagIds = Tag::getTagIds($request->input('tags'));
        if (count($tagIds)) {
            $post->tags()->attach($tagIds);
        }
        //文章发布事件
        event(new PostChange($post->id, 'create'));
        //返回结果
        return redirect()->route('post.show', $post->slug)->with('success', '文章发表成功！');
    }

    /**
     * Display the specified resource.
     *
     * @param Post $post
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show(Post $post)
    {
        $this->authorize('show', $post);
        $data = Cache::rememberForever('post:' . $post->id, function () use ($post) {
            $data = $post->load('user', 'tags', 'comments')->loadCount('favorites');
            $data->comments->load('user')->loadCount('favorites');
            return compact('post');
        });
        if (empty($post->password) || $this->authorize('update', $post)) {
            $post->visits()->increment();
            return view('posts.show', $data);
        } else {
            $unlock = session("post-{$post->id}", false);
            if ($unlock) {
                return view('posts.show', $data);
            }
            return view('posts.password', $data);
        }
    }

    /**
     * unlock the post
     * @param Post $post
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function unlock(Post $post, Request $request)
    {
        $password = $request->input('password');
        if ($post->password == $password) {
            session(["post-{$post->id}" => true]);
            return redirect()->route('post.show', $post->slug);
        } else {
            return redirect()->back()->with('error', '访问密码不正确');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Post $post
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(Post $post)
    {
        $this->authorize('update', $post);
        $tags = $post->tags->implode('name', ', ');
        $alltags = Tag::all()->pluck('name')->toJson(JSON_UNESCAPED_UNICODE);
        return view('posts.edit', compact('post', 'tags', 'alltags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param Post $post
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(Request $request, Post $post)
    {
        $this->authorize('update', $post);
        //封面图处理
        if ($file = $request->cover) {
            // 保存图片到本地
            $result = Upload::file($request->file('cover'), 'cover');
            Upload::reduceSize($result['path'], 1024, null, true);
            // 图片保存成功的话
            if ($result) {
                $post->cover = $result['path'];
            }
        }

        //更新文章
        $post->title = $request->input('title');
        $post->keyword = str_replace(' ', '', $request->input('tags'));
        $post->description = $request->input('description');
        $post->content = $request->input('content');
        $post->category_id = $request->input('category_id');
        $post->status = $request->input('status');
        if ($request->input('publish_time')) {
            $post->publish_time = strtotime($request->input('publish_time'));
        }
        $post->password = $request->input('password');
        $post->allow_comment = $request->input('allow_comment');
        $post->save();
        //标签关联
        $tagIds = Tag::getTagIds($request->input('tags'));
        $post->tags()->sync($tagIds);
        //文章更新事件
        event(new PostChange($post->id, 'update'));
        //返回结果
        return redirect()->route('post.show', $post->slug)->with('success', '文章修改成功！');
    }

    public function restore()
    {
        $post = Post::withTrashed()->findOrFail(request()->id);
        $this->authorize('update', $post);
        $post->restore();
        return ['code' => 0, 'msg' => '恢复成功'];
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return array
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy($id)
    {
        $post = Post::withTrashed()->findOrFail($id);
        $this->authorize('update', $post);
        if (request()->force == 'true') {
            $tag_ids = $post->tags->pluck('id')->all();
            $post->tags()->detach();
            foreach ($tag_ids as $k => $v) {
                $tag = Tag::find($v);
                if ($tag->posts->count() == 0) {
                    $tag->delete();
                }
            }
            $post->comments()->delete();
            $post->forceDelete();
        } else {
            $post->delete();
            event(new PostChange($post->id, 'delete'));
        }
        return ['code' => 0, 'msg' => '删除成功'];
    }

    public function search(Request $request)
    {
        $page = $request->input('page', 1);
        $keyword = $request->keyword;
        $posts = Cache::remember('search:' . $keyword . ':' . $page, 3600, function () use ($keyword) {
            $lists = Post::search($keyword)->orderBy('id', 'desc')->paginate(12);
            $lists->load('user', 'tags')->loadCount(['comments', 'favorites']);
            return $lists;
        });
        return view('posts.search', compact('posts', 'keyword'));
    }

}

resources/views/posts/create.blade.php
@extends('layouts.app')
@section('title',  __('CreatePost').' - '.sysConfig('SITE_NAME'))

@section('styles')
  <link rel="stylesheet" type="text/css" href="{{ asset('lib/editormd/css/editormd.min.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ asset('lib/tagator/fm.tagator.jquery.min.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ asset('lib/dropify/dropify.min.css') }}">
@stop

@section('body')

  <!-- start navigation -->
  @include('layouts._nav')
  <!-- end navigation -->

  <!-- start site's main /content area -->
  <section class="content-wrap">
    <div class="container">
      <div class="row">
        <!-- start main area -->
        <div class="col-12">
          <div class="card mb-5">
            <div class="card-header text-center">
              <i class="icon paint brush"></i> {{__('CreatePost')}}
            </div>
            <div class="card-body">
              <!-- start navigation -->
            @include('layouts._msg')
            <!-- end navigation -->
              <form id="post" method="post" action="{{ route('post.store') }}" enctype="multipart/form-data">
                @method('POST')
                @csrf
                <div class="form-group">
                  <label for="title">文章标题</label>
                  <input type="text"
                         class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}"
                         id="title"
                         name="title" placeholder="文章标题">
                  @if ($errors->has('title'))
                    <span class="invalid-feedback"
                          role="alert"><strong>{{ $errors->first('title') }}</strong></span>
                  @endif
                </div>
                <div class="form-group">
                  <label for="category">文章分类</label>
                  <select class="form-control" id="category" name="category_id">
                    @foreach($cats as $cat)
                      <option value="{{$cat->id}}">{{$cat->name}}</option>
                    @endforeach
                  </select>
                </div>
                <div class="form-group">
                  <label for="tags" data-toggle="tooltip" title="输入完标签请按回车" data-placement="right">文章标签</label>
                  <textarea class="form-control" id="tags" name="tags"></textarea>
                </div>
                <div class="form-group">
                  <label for="cover">封面图</label>
                  <input type="file" class="form-control dropify" id="cover" name="cover"
                         data-allowed-file-extensions="jpg jpeg png gif bmp webp">
                </div>
                <div class="form-group">
                  <label for="description">文章描述</label>
                  <textarea class="form-control" id="description" name="description" rows="3"
                            placeholder="请简要概述大概内容，不要超过150字" maxlength="150"></textarea>
                </div>
                <div class="form-group" id="editor">
                  <textarea name="content" id="content" class="form-control"></textarea>
                </div>
                <div class="row mb-3">
                  <div class="col">
                    <label for="publish_time">定时发布</label>
                    <input id="publish_time" name="publish_time" type="text" class="form-control"
                           autocomplete="off" placeholder="不定时发表请留空" />
                  </div>
                  <div class="col">
                    <label for="password">文章密码</label>
                    <input id="password" name="password" type="text" class="form-control" placeholder="不加密请留空" />
                  </div>
                  <div class="col">
                    <label for="allow_comment">可否评论</label>
                    <select class="form-control" id="allow_comment" name="allow_comment">
                      <option value="1">可被评论</option>
                      <option value="0">禁止评论</option>
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="status" id="publish" value="1" checked>
                    <label class="form-check-label" for="publish">
                      直接发布
                    </label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="status" id="draft" value="0">
                    <label class="form-check-label" for="draft">
                      保存为草稿
                    </label>
                  </div>
                </div>
                <div class="form-group">
                  <button type="submit" class="btn btn-success">提交</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!-- end main area -->
      </div>
    </div>
  </section>
  <!-- end site's main /content area -->

  <!-- start main-footer -->
  @include('layouts._footer')
  <!-- end main-footer -->

@endsection

@section('scripts')
  <script type="text/javascript" src="{{ asset('lib/tagator/fm.tagator.jquery.js') }}"></script>
  <script type="text/javascript" src="{{ asset('lib/dropify/dropify.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('lib/editormd/editormd.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('lib/laydate/laydate.js') }}"></script>
  <script>
    $(function () {

      $('#tags').tagator({
        autocomplete: {!! $tags !!}
      });

      laydate.render({elem: '#publish_time',type: 'datetime'});

      $('#cover').dropify({
        messages: {
          'default': '单击此处或者拖动图片到此处',
          'replace': '单击此处或者拖动图片到此处更换图片',
          'remove': '移除',
          'error': '哦豁，发生了一点意外。'
        }
      });

      var editor = editormd("editor", {
        width: "100%",
        height: "500px",
        // lineNumbers:false,
        watch : false,
        codeFold : true,
        placeholder:"请在这撰写您的文章内容...",
        taskList: true,
        emoji:true,
        flowChart: true,
        sequenceDiagram: true,
        imageUpload: true,
        imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
        imageUploadURL : "{{ route('upload.store') }}",
        path : "/lib/editormd/lib/"
      });

    });

  </script>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('title', '文章管理 - '.sysConfig('SITE_NAME'))
@section('body')

  <!-- start navigation -->
  @include('layouts._nav')
  <!-- end navigation -->

  <!-- start site's main /content area -->
  <section class="content-wrap">
    <div class="container">
      <div id="profile" class="row">
        <!-- start main area -->
        <div class="col-3">
          <ul class="list-group text-center">
            <li class="list-group-item">
              <a href="{{ route('setting.index')}}"><i class="fa fa-cog fa-fw" aria-hidden="true"></i>
                系统设置</a>
            </li>
            <li class="list-group-item active">
              <a href="{{ route('post.manage') }}"><i class="fa fa-file-text fa-fw" aria-hidden="true"></i>
                文章管理</a>
            </li>
            <li class="list-group-item">
              <a href="{{ route('category.index') }}"><i class="fa fa-folder-open fa-fw" aria-hidden="true"></i>
                分类管理</a>
            </li>
            <li class="list-group-item">
              <a href="{{ route('link.index') }}"><i class="fa fa-link fa-fw" aria-hidden="true"></i>
                友链管理</a>
            </li>
          </ul>
        </div>
        <div class="col-9">
          <div class="card">
            <div class="card-header">
              <i class="fa fa-file-text" aria-hidden="true"></i> 文章管理
            </div>
            <div class="card-body">
              <!-- start message tips -->
            @include('layouts._msg')
            <!-- end message tips -->

              <div class="dropdown show mb-2">
                <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  条件筛选
                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a class="dropdown-item" href="{{route('post.manage',['type'=>'all'])}}" data-toggle="tooltip"
                     data-placement="right" title="不包含被删除的文章">所有文章</a>
                  <a class="dropdown-item" href="{{route('post.manage',['type'=>'published'])}}" data-toggle="tooltip"
                     data-placement="right" title="显示已被发表的文章">已发表的文章</a>
                  <a class="dropdown-item" href="{{route('post.manage',['type'=>'draft'])}}" data-toggle="tooltip"
                     data-placement="right" title="显示保存为草稿的文章">草稿箱文章</a>
                  <a class="dropdown-item" href="{{route('post.manage',['type'=>'recycle'])}}" data-toggle="tooltip"
                     data-placement="right" title="显示已被删除了的文章">回收站文章</a>
                </div>
              </div>

              <table class="table table-bordered table-hover table-sm">
                <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">标题</th>
                  <th scope="col">操作</th>
                </tr>
                </thead>
                <tbody>
                @foreach($posts as $post)
                  <tr>
                    <th scope="row">{{ $post->id }}</th>
                    <td>{{ $post->title }}</td>
                    <td>
                      @if($type!='recycle')
                        <a href="{{ route('post.edit',$post->slug) }}" class="btn btn-default btn-sm">编辑</a>
                        <button class="btn btn-danger btn-sm delete" data-id="{{$post->id}}">删除</button>
                      @else
                        <button class="btn btn-default btn-sm restore" data-id="{{$post->id}}">恢复</button>
                        <button class="btn btn-danger btn-sm forceDelete" data-id="{{$post->id}}">彻底删除</button>
                      @endif
                    </td>
                  </tr>
                @endforeach
                </tbody>
              </table>

              {{$posts->appends(['type' => $type])->links()}}

            </div>
          </div>
        </div>
        <!-- end main area -->
      </div>
    </div>
  </section>
  <!-- end site's main /content area -->

  <!-- start main-footer -->
  @include('layouts._footer')
  <!-- end main-footer -->

@endsection

@section('scripts')
  <script>
      $(function () {
          $(".delete").click(function () {
              var id = $(this).data('id');
              swal({
                  title: "确定要删除吗?",
                  text: "删除后可从回收站恢复!",
                  icon: "warning",
                  buttons: ["取消操作", "确定删除"],
                  dangerMode: true,
              })
                  .then((willDelete) => {
                      if (willDelete) {
                          axios({
                              method: 'delete',
                              url: '/post/' + id
                          }).then(function (response) {
                              swal(response.data.msg, {
                                  icon: response.data.code == 0 ? "success" : "error",
                              }).then(function () {
                                  if (response.data.code == 0) {
                                      document.location.reload();
                                  }
                              });
                          });
                      }
                  });
          });

          $(".restore").click(function () {
              var id = $(this).data('id');
              swal({
                  title: "确定要恢复吗?",
                  text: "",
                  icon: "warning",
                  buttons: ["取消操作", "确定恢复"],
                  dangerMode: true,
              })
                  .then((willDelete) => {
                      if (willDelete) {
                          axios({
                              method: 'patch',
                              url: '/post/restore',
                              data: {
                                  'id': id
                              }
                          }).then(function (response) {
                              swal(response.data.msg, {
                                  icon: response.data.code == 0 ? "success" : "error",
                              }).then(function () {
                                  if (response.data.code == 0) {
                                      document.location.reload();
                                  }
                              });
                          });
                      }
                  });
          });

          $(".forceDelete").click(function () {
              var id = $(this).data('id');
              swal({
                  title: "确定要删除吗?",
                  text: "一旦删除无法恢复!",
                  icon: "warning",
                  buttons: ["取消操作", "确定删除"],
                  dangerMode: true,
              })
                  .then((willDelete) => {
                      if (willDelete) {
                          axios({
                              method: 'delete',
                              url: '/post/' + id,
                              data: {
                                  'force': true
                              }
                          }).then(function (response) {
                              swal(response.data.msg, {
                                  icon: response.data.code == 0 ? "success" : "error",
                              }).then(function () {
                                  if (response.data.code == 0) {
                                      document.location.reload();
                                  }
                              });
                          });
                      }
                  });
          });

      });
  </script>
@endsection

resources/views/posts/password.blade.php
@extends('layouts.app')
@section('title', $post->title.' - '.sysConfig('SITE_NAME'))
@section('keyword', $post->keyword)
@section('description', $post->description)

@section('body')

  <!-- start navigation -->
  @include('layouts._nav')
  <!-- end navigation -->

  <!-- start site's main /content area -->
  <div class="container">
    <div class="row justify-content-center login">
      <div class="col-md-8">
        @if(session('error'))
          <div class="alert alert-danger" role="alert">
            {{ session('error')}}
          </div>
        @endif
        <div class="card">
          <div class="card-header">这是一篇私密的文章</div>

          <div class="card-body">
            <form method="POST" action="{{ route('post.unlock',$post->slug) }}">
              @csrf

              <div class="form-group row">
                <label for="password" class="col-md-4 col-form-label text-md-right">访问密码</label>

                <div class="col-md-6">
                  <input id="password" type="password" class="form-control" name="password" required>
                </div>
              </div>

              <div class="form-group row mb-0">
                <div class="col-md-8 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                    解锁
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- end site's main /content area -->

  <!-- start main-footer -->
  @include('layouts._footer')
  <!-- end main-footer -->

@endsection