routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PostsController@index')->name('index');
Route::get('manifest.json', 'PagesController@manifest');
Route::get('sitemap.xml', 'PagesController@sitemap')->name('sitemap');
Route::get('feed', 'PagesController@feed')->name('feed');

Route::get('/tag/{tag}', 'TagsController@show')->name('tag.show');
Route::get('/tags', 'TagsController@index')->name('tags');
Route::resource('category', 'CategoriesController');
Route::patch('/post/restore', 'PostsController@restore')->name('post.restore');
Route::post('/post/{post}/unlock', 'PostsController@unlock')->name('post.unlock');
Route::resource('post', 'PostsController');
Route::resource('comment', 'CommentsController', ['only' => ['store', 'destroy']])->middleware('auth');
Route::post('/favorites/comment/{comment}', 'FavoritesController@comment');
Route::post('/favorites/post/{post}', 'FavoritesController@post');
Route::post('/subscribe', 'SubscribesController@store');
Route::get('/search/{keyword}', 'PostsController@search')->name('post.search');

Route::get('upload', 'FilesController@index')->name('upload.index');
Route::post('upload', 'FilesController@store')->name('upload.store');
Route::delete('upload', 'FilesController@destroy')->name('upload.destroy');

Auth::routes(['verify' => true]);
Route::resource('notifications', 'NotificationsController', ['only' => ['index']]);
Route::post('/at', 'UsersController@index');
Route::get('/user/{user}', 'UsersController@show')->name('user.show');
Route::get('/user/{user}/edit', 'UsersController@edit')->name('user.edit');
Route::put('/user/{user}/edit', 'UsersController@update')->name('user.update');
Route::match(['get', 'put'], '/user/{user}/avatar', 'UsersController@avatar')->name('user.avatar');
Route::match(['get', 'put'], '/user/{user}/password', 'UsersController@password')->name('user.password');
Route::match(['get', 'put'], '/user/{user}/binding', 'UsersController@binding')->name('user.binding');
Route::match(['get', 'put'], '/user/{user}/paycode', 'UsersController@paycode')->name('user.paycode');

Route::resource('link', 'LinksController');
Route::get('setting', 'SettingsController@index')->name('setting.index');
Route::put('setting', 'SettingsController@update')->name('setting.update');
Route::get('/posts', 'PostsController@list')->name('post.manage');
Route::get('clear', 'SettingsController@clear')->name('setting.clear');

Route::post('pay/alipay/create', 'Pay\AlipayController@create');
Route::get('pay/alipay/return', 'Pay\AlipayController@return');
Route::post('pay/alipay/notify', 'Pay\AlipayController@notify');
Route::get('pay/alipay/{order}', 'Pay\AlipayController@pay');
Route::post('pay/wechat/pay', 'Pay\WechatController@pay');
Route::post('pay/wechat/notify', 'Pay\WechatController@notify');

app/Models/Link.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    protected $fillable = [
        'name', 'url', 'sort',
    ];
}

app/Http/Controllers/Api/LinksController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Link;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cache;

class LinksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $friend_links = Cache::rememberForever('links', function () {
            return Link::all();
        });
        return $friend_links;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/LinksController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LinkRequest;
use App\Models\Link;

class LinksController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function index()
    {
        $this->authorize('update', Link::class);
        $links = Link::paginate(12);
        return view('links.index', compact('links'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        $this->authorize('update', Link::class);
        return view('links.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param LinkRequest $request
     * @param Link $link
     * @return void
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function store(LinkRequest $request, Link $link)
    {
        $this->authorize('update', Link::class);
        $link->fill($request->all());
        $link->save();
        return redirect()->route('link.index')->with('success', '添加友链成功！');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Link $link
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(Link $link)
    {
        $this->authorize('update', Link::class);
        return view('links.edit', compact('link'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param LinkRequest $request
     * @param Link $link
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(LinkRequest $request, Link $link)
    {
        $this->authorize('update', Link::class);
        $link->update($request->all());
        return redirect()->route('link.index')->with('success', '修改友链成功！');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Link $link
     * @return array
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy(Link $link)
    {
        $this->authorize('update', Link::class);
        $link->delete();
        return ['code' => 0, 'msg' => '删除成功'];
    }
}

resources/views/links/create.blade.php
@extends('layouts.app')
@section('title', '添加友链 - '.sysConfig('SITE_NAME'))
@section('body')

  <!-- start navigation -->
  @include('layouts._nav')
  <!-- end navigation -->

  <!-- start site's main /content area -->
  <section class="content-wrap">
    <div class="container">
      <div id="profile" class="row">
        <!-- start main area -->
        <div class="col-3">
          <ul class="list-group text-center">
            <li class="list-group-item">
              <a href="{{ route('setting.index')}}"><i class="fa fa-cog" aria-hidden="true"></i>
                系统设置</a>
            </li>
            <li class="list-group-item">
              <a href="{{ route('category.index') }}"><i class="fa fa-folder-open" aria-hidden="true"></i>
                分类管理</a>
            </li>
            <li class="list-group-item active">
              <a href="{{ route('link.index') }}"><i class="fa fa-link" aria-hidden="true"></i>
                友链管理</a>
            </li>
          </ul>
        </div>
        <div class="col-9">
          <div class="card">
            <div class="card-header">
              <i class="fa fa-folder-open" aria-hidden="true"></i> 添加友链
            </div>
            <div class="card-body">
              <!-- start message tips -->
            @include('layouts._msg')
            <!-- end message tips -->

              <form action="{{ route('link.store') }}" method="post">
                @csrf
                <div class="form-group">
                  <label for="name">友链名称</label>
                  <input type="text" class="form-control" id="name" name="name" placeholder="请输入友链名称" required>
                </div>
                <div class="form-group">
                  <label for="url">友链网址</label>
                  <input type="url" class="form-control" id="url" name="url" placeholder="请输入友链网址" required>
                </div>
                <div class="form-group">
                  <label for="sort">排序</label>
                  <input type="number" class="form-control" id="sort" name="sort" placeholder="越小越靠前" required>
                </div>
                <button type="submit" class="btn btn-primary">提交</button>
                <a href="javascript:history.go(-1);" class="btn btn-secondary">返回</a>
              </form>

            </div>
          </div>
        </div>
        <!-- end main area -->
      </div>
    </div>
  </section>
  <!-- end site's main /content area -->

  <!-- start main-footer -->
  @include('layouts._footer')
  <!-- end main-footer -->

@endsection

resources/views/links/edit.blade.php
@extends('layouts.app')
@section('title', '编辑友链 - '.sysConfig('SITE_NAME'))
@section('body')

  <!-- start navigation -->
  @include('layouts._nav')
  <!-- end navigation -->

  <!-- start site's main /content area -->
  <section class="content-wrap">
    <div class="container">
      <div id="profile" class="row">
        <!-- start main area -->
        <div class="col-3">
          <ul class="list-group text-center">
            <li class="list-group-item">
              <a href="{{ route('setting.index')}}"><i class="fa fa-cog" aria-hidden="true"></i>
                系统设置</a>
            </li>
            <li class="list-group-item">
              <a href="{{ route('category.index') }}"><i class="fa fa-folder-open" aria-hidden="true"></i>
                分类管理</a>
            </li>
            <li class="list-group-item active">
              <a href="{{ route('link.index') }}"><i class="fa fa-link" aria-hidden="true"></i>
                友链管理</a>
            </li>
          </ul>
        </div>
        <div class="col-9">
          <div class="card">
            <div class="card-header">
              <i class="fa fa-folder-open" aria-hidden="true"></i> 编辑友链
            </div>
            <div class="card-body">
              <!-- start message tips -->
            @include('layouts._msg')
            <!-- end message tips -->

              <form action="{{ route('link.update',$link->id) }}" method="post">
                @method('PUT')
                @csrf
                <div class="form-group">
                  <label for="name">友链名称</label>
                  <input type="text" class="form-control" id="name" name="name" value="{{$link->name}}" required>
                </div>
                <div class="form-group">
                  <label for="url">友链网址</label>
                  <input type="url" class="form-control" id="url" name="url" value="{{$link->url}}" required>
                </div>
                <div class="form-group">
                  <label for="sort">排序</label>
                  <input type="number" class="form-control" id="sort" name="sort" value="{{$link->sort}}" required>
                </div>
                <button type="submit" class="btn btn-primary">提交</button>
                <a href="javascript:history.go(-1);" class="btn btn-secondary">返回</a>
              </form>

            </div>
          </div>
        </div>
        <!-- end main area -->
      </div>
    </div>
  </section>
  <!-- end site's main /content area -->

  <!-- start main-footer -->
  @include('layouts._footer')
  <!-- end main-footer -->

@endsection

resources/views/links/index.blade.php
@extends('layouts.app')
@section('title', '友链管理 - '.sysConfig('SITE_NAME'))
@section('body')

  <!-- start navigation -->
  @include('layouts._nav')
  <!-- end navigation -->

  <!-- start site's main /content area -->
  <section class="content-wrap">
    <div class="container">
      <div id="profile" class="row">
        <!-- start main area -->
        <div class="col-3">
          <ul class="list-group text-center">
            <li class="list-group-item">
              <a href="{{ route('setting.index')}}"><i class="fa fa-cog" aria-hidden="true"></i>
                系统设置</a>
            </li>
            <li class="list-group-item">
              <a href="{{ route('post.manage') }}"><i class="fa fa-file-text" aria-hidden="true"></i>
                文章管理</a>
            </li>
            <li class="list-group-item">
              <a href="{{ route('category.index') }}"><i class="fa fa-folder-open" aria-hidden="true"></i>
                分类管理</a>
            </li>
            <li class="list-group-item active">
              <a href="{{ route('link.index') }}"><i class="fa fa-link" aria-hidden="true"></i>
                友链管理</a>
            </li>
          </ul>
        </div>
        <div class="col-9">
          <div class="card">
            <div class="card-header">
              <i class="fa fa-link" aria-hidden="true"></i> 友链管理
            </div>
            <div class="card-body">
              <!-- start message tips -->
            @include('layouts._msg')
            <!-- end message tips -->

              <a href="{{ route('link.create') }}" class="btn btn-default btn-sm mb-2">添加友链</a>
              <table class="table table-bordered table-hover table-sm">
                <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">友链名称</th>
                  <th scope="col">友链网址</th>
                  <th scope="col">排序</th>
                  <th scope="col">操作</th>
                </tr>
                </thead>
                <tbody>
                @foreach($links as $link)
                  <tr>
                    <th scope="row">{{ $link->id }}</th>
                    <td>{{ $link->name }}</td>
                    <td>{{ $link->url }}</td>
                    <td>{{ $link->sort }}</td>
                    <td>
                      <a href="{{ route('link.edit',$link->id) }}" class="btn btn-default btn-sm">编辑</a>
                      <button class="btn btn-danger btn-sm delete" data-id="{{$link->id}}">删除</button>
                    </td>
                  </tr>
                @endforeach
                </tbody>
              </table>

            </div>
          </div>
        </div>
        <!-- end main area -->
      </div>
    </div>
  </section>
  <!-- end site's main /content area -->

  <!-- start main-footer -->
  @include('layouts._footer')
  <!-- end main-footer -->

@endsection

@section('scripts')
  <script>
    $(function () {
      $(".delete").click(function () {
        var id = $(this).data('id');
        swal({
          title: "确定要删除吗?",
          text: "一旦删除无法恢复!",
          icon: "warning",
          buttons: ["取消操作", "确定删除"],
          dangerMode: true,
        })
          .then((willDelete) => {
            if (willDelete) {
              axios({
                method: 'delete',
                url: '/link/' + id
              }).then(function (response) {
                swal(response.data.msg, {
                  icon: response.data.code == 0 ? "success" : "error",
                }).then(function () {
                  if (response.data.code == 0) {
                    document.location.reload();
                  }
                });
              });
            }
          });
      });
    });
  </script>
@endsection