routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PostsController@index')->name('index');
Route::get('manifest.json', 'PagesController@manifest');
Route::get('sitemap.xml', 'PagesController@sitemap')->name('sitemap');
Route::get('feed', 'PagesController@feed')->name('feed');

Route::get('/tag/{tag}', 'TagsController@show')->name('tag.show');
Route::get('/tags', 'TagsController@index')->name('tags');
Route::resource('category', 'CategoriesController');
Route::patch('/post/restore', 'PostsController@restore')->name('post.restore');
Route::post('/post/{post}/unlock', 'PostsController@unlock')->name('post.unlock');
Route::resource('post', 'PostsController');
Route::resource('comment', 'CommentsController', ['only' => ['store', 'destroy']])->middleware('auth');
Route::post('/favorites/comment/{comment}', 'FavoritesController@comment');
Route::post('/favorites/post/{post}', 'FavoritesController@post');
Route::post('/subscribe', 'SubscribesController@store');
Route::get('/search/{keyword}', 'PostsController@search')->name('post.search');

Route::get('upload', 'FilesController@index')->name('upload.index');
Route::post('upload', 'FilesController@store')->name('upload.store');
Route::delete('upload', 'FilesController@destroy')->name('upload.destroy');

Auth::routes(['verify' => true]);
Route::resource('notifications', 'NotificationsController', ['only' => ['index']]);
Route::post('/at', 'UsersController@index');
Route::get('/user/{user}', 'UsersController@show')->name('user.show');
Route::get('/user/{user}/edit', 'UsersController@edit')->name('user.edit');
Route::put('/user/{user}/edit', 'UsersController@update')->name('user.update');
Route::match(['get', 'put'], '/user/{user}/avatar', 'UsersController@avatar')->name('user.avatar');
Route::match(['get', 'put'], '/user/{user}/password', 'UsersController@password')->name('user.password');
Route::match(['get', 'put'], '/user/{user}/binding', 'UsersController@binding')->name('user.binding');
Route::match(['get', 'put'], '/user/{user}/paycode', 'UsersController@paycode')->name('user.paycode');

Route::resource('link', 'LinksController');
Route::get('setting', 'SettingsController@index')->name('setting.index');
Route::put('setting', 'SettingsController@update')->name('setting.update');
Route::get('/posts', 'PostsController@list')->name('post.manage');
Route::get('clear', 'SettingsController@clear')->name('setting.clear');

Route::post('pay/alipay/create', 'Pay\AlipayController@create');
Route::get('pay/alipay/return', 'Pay\AlipayController@return');
Route::post('pay/alipay/notify', 'Pay\AlipayController@notify');
Route::get('pay/alipay/{order}', 'Pay\AlipayController@pay');
Route::post('pay/wechat/pay', 'Pay\WechatController@pay');
Route::post('pay/wechat/notify', 'Pay\WechatController@notify');

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Cache::remember('tags', 3600, function () {
            return Tag::all();
        });
        return view('pages.tags', compact('tags'));
    }

    /**
     * Display the specified resource.
     *
     * @param Tag $tag
     * @param Request $request
     * @return void
     */
    public function show(Tag $tag, Request $request)
    {
        $page = $request->input('page', 1);
        $posts = Cache::tags(['tag-post'])->rememberForever('tag:' . $tag->id . ':' . $page, function () use ($tag) {
            return $tag->posts()->with(['user', 'tags'])->withCount(['comments','favorites'])->orderBy('id', 'desc')->paginate(12);
        });
        return view('pages.tag', compact('posts', 'tag'));
    }

}

resources/views/layouts/_comment.blade.php
<div class="post-author media mb-4">
  <img class="mr-3 avatar rounded-circle" src="{{$post->user->avatar}}" alt="{{$post->user->name}}">
  <div class="media-body">
    <h5 class="mt-0">
      <a class="user-link mr-2" href="{{route('user.show',$post->user->name)}}" target="_blank" data-toggle="tooltip"
         data-placement="bottom" title="" data-original-title="查看{{$post->user->name}}发表的文章">{{$post->user->name}}</a>
      @if(!empty($post->user->extend->qq))
      <a href="tencent://message/?uin={{$post->user->extend->qq}}" class="trd"><i class="fa fa-qq"></i></a>
      @endif
      @if(!empty($post->user->extend->wechat))
      <a id="wechat" data-url="{{$post->user->extend->wechat}}" class="trd"><i class="fa fa-weixin"></i></a>
      @endif
      @if(!empty($post->user->extend->github))
      <a href="{{$post->user->extend->weibo}}" class="trd"><i class="fa fa-weibo"></i></a>
      @endif
      @if(!empty($post->user->extend->github))
        <a href="{{$post->user->extend->github}}" class="trd"><i class="fa fa-github"></i></a>
      @endif
    </h5>
    <p>{{$post->user->bio}}</p>
  </div>
</div>
<div class="post-comment-bar" id="comments">
  <h4 class="mb-0">
                <span class="badge badge-primary">
                   <i class="fa fa-comments" aria-hidden="true"></i> 评论
                </span>
  </h4>
  <div class="clearfix"></div>
</div>
@forelse ($post->comments as $key=> $comment)
  <div class="post-comment media" id="comment{{$comment->id}}" name="comment{{$comment->id}}">
    <img class="mr-3 avatar rounded-circle" src="{{$comment->user->avatar}}"
         alt="{{$comment->user->name}}">
    <div class="media-body">
      <h5 class="mt-0">
        <a class="user-link" href="{{ route('user.show',$comment->user->name) }}"
           target="_blank" data-toggle="tooltip" data-placement="bottom"
           title="查看{{$comment->user->name}}发表的文章">{{$comment->user->name}}</a>
        <span class="ml-2 time" title="{{ $comment->created_at->toDateTimeString() }}">
                       {{ $comment->created_at->diffForHumans() }}
                  </span>
        <span class="float-right h6 time">#{{$key+1}}</span>
      </h5>
      <p>{!! $comment->content !!}</p>
      <span>
                    <div class="float-left favorite" data-id="{{$comment->id}}" data-toggle="tooltip"
                         data-placement="bottom" title="点赞这条评论">
                         <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                      赞(<span class="num">{{ $comment->favorites_count }}</span>)
                    </div>
                    <div class="float-left reply" data-name="{{$comment->user->name}}" data-toggle="tooltip"
                         data-placement="bottom" title="回复{{$comment->user->name}}">
                         <i class="fa fa-reply" aria-hidden="true"></i> 回复
                    </div>
                    @can('delete',$comment)
          <div class="float-right delete" data-id="{{$comment->id}}" data-toggle="tooltip"
               data-placement="bottom" title="删除该评论">
                         <i class="fa fa-trash-alt" aria-hidden="true"></i> 删除
                    </div>
        @endcan
                </span>
    </div>
  </div>
@empty
  <div class="post-comment text-center">
    <h5 class="p-3">(=￣ω￣=)··· 暂无内容！</h5>
  </div>
@endforelse
<div class="post-comment-bar mt-4" id="reply-wrap">
  <h4 class="mb-0">
              <span class="badge badge-primary">
                   <i class="fa fa-reply" aria-hidden="true"></i> 回复
              </span>
  </h4>
  <div class="clearfix"></div>
</div>
<div class="post-reply p-2 mb-5" id="post-reply" data-allow-coment="{{$post->getOriginal('allow_comment')}}">
  @auth
    @if($post->allow_comment)
      <form id="comment-form" action="{{route('comment.store')}}" method="post">
        <div class="form-group">
          <input type="hidden" name="_token" value="{{ csrf_token() }}">
          <input id="post_id" type="hidden" name="post_id" value="{{ $post->id }}">
        </div>
        <div class="form-group" id="reply">
                  <textarea name="reply_content" id="reply_content" class="form-control" rows="5"
                            placeholder="请输入您要评论的内容..." required></textarea>
        </div>
        @if(sysConfig('VERIFY_COMMENT') == 'true')
          <div class="form-group">
            <input id="verify_token" type="hidden" name="token" />
            <div id="vaptchaContainer" data-id="{{sysConfig('VAPTCHA_VID')}}">
              验证码加载中...
            </div>
          </div>
        @endif
        <div class="form-group m-0">
          <button id="submit-comment" type="button" class="btn btn-default btn-block">提交评论</button>
        </div>
      </form>
    @else
      <div class="d-flex justify-content-center mt-5 mb-5">
        <h5>作者未开启此文的评论功能</h5>
      </div>
    @endif
  @else
    <div class="d-flex justify-content-center mt-5 mb-5">
      <h5>您还未登录,请先<a href="{{route('login')}}">登录</a>或者<a href="{{route('register')}}">注册</a>
      </h5>
    </div>
  @endauth
</div>

resources/views/layouts/_footer.blade.php
<footer id="footer-warp">
    <!-- start main-footer -->
    <div id="footer" class="container-fluid">
        <div class="container">
            <div class="row">
                <!-- start first footer widget area -->
                <div class="col-sm">
                    <!-- start widget -->
                    <div class="widget">
                        <h4 class="title">最热文章</h4>
                        <div class="content recent-post">
                            @foreach($hot_posts as $post)
                                <div class="recent-single-post">
                                    <a href="{{route('post.show',$post->slug)}}"
                                       class="post-title">{{$post->title}}</a>
                                    <div class="date">{{$post->created_at->toDateTimeString()}}</div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <!-- end widget -->
                </div>
                <!-- end first footer widget area -->

                <!-- start second footer widget area -->
                <div class="col-sm">
                    <!-- start tag cloud widget -->
                    <div class="widget">
                        <h4 class="title">标签云</h4>
                        <div class="content tag-cloud">
                            @foreach($top_tags as $tag)
                                <a href="{{route('tag.show',$tag->name)}}">{{$tag->name}}</a>
                            @endforeach
                            <a href="{{route('tags')}}">...</a>
                        </div>
                    </div>
                    <!-- end tag cloud widget -->
                </div>
                <!-- end second footer widget area -->

                <!-- start third footer widget area -->
                <div class="col-sm">
                    <!-- start widget -->
                    <div class="widget">
                        <h4 class="title">友情链接</h4>
                        <div class="content friend-links">
                            @foreach($links as $link)
                                <a href="{{ $link->url }}" target="_blank">{{ $link->name }}</a>
                            @endforeach
                        </div>
                    </div>
                    <!-- end widget -->
                </div>
                <!-- end third footer widget area -->
            </div>
        </div>
    </div>
    <!-- start main-footer  -->

    <!-- start copyright section -->
    <div id="copyright" class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <span>Copyright &copy; <a href="{{ config('app.url') }}">{{ sysConfig('SITE_NAME') }}</a> All right Reserved.
                      Powered By <a href="https://github.com/inbjo/CoreBlog" target="_blank">CoreBlog</a></span>
                </div>
            </div>
            <div class="row mt-1">
                <div class="col-12">
                    <span><a href="{{ route('sitemap') }}" target="_blank">网站地图</a></span>
                    <span></span>
                    <span>
                    <a href="{{ route('feed') }}" target="_blank">RSS</a>
                </span>
                    <span></span>
                    <span>
                    <a href="http://www.beian.miit.gov.cn" target="_blank">{{ sysConfig('SITE_ICP') }}</a>
                </span>
                    <span></span>
                    <span>
                    <a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode={{ getPoliceNumber() }}"
                       target="_blank">{{ sysConfig('SITE_POLICE') }}</a>
                </span>
                </div>
            </div>
        </div>
    </div>
    <!-- end copyright section -->

    <!-- start back-to-top -->
    <a id="back-to-top" href="javascript:void(0);"><i class="fa fa-angle-up"></i></a>
    <!-- end back-to-top -->
</footer>

resources/views/layouts/_js.blade.php
<script>
  var is_login = @if(auth()->check())true @else false @endif;
</script>

resources/views/layouts/_main.blade.php
<div class="col-12 col-sm-12 col-md-12 col-lg-8 col-xl-8 main-content">
    <!-- start message tips -->
    @include('layouts._msg')
    <!-- end message tips -->

    <div id="pwaTip" class="alert alert-light d-none" role="alert">
      温馨提醒:本站支持PWA，点击我可安装到桌面。
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <!-- start post -->
    @include('layouts._post')
    <!-- end post -->

    <!-- start pagination -->
    @include('layouts._paginate')
    <!-- end pagination -->

</div>

resources/views/layouts/_msg.blade.php
@if ($errors->any())
  <div class="alert alert-danger" role="alert">
    <ul>
      @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

@foreach (['danger', 'warning', 'success', 'info'] as $msg)
  @if(session()->has($msg))
    <div class="flash-message">
      <div class="alert alert-{{ $msg }} alert-dismissible fade show" role="alert">
        {{ session()->get($msg) }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  @endif
@endforeach

resources/views/layouts/_nav.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-static-top">
    <div class="container">
        <!-- Branding Image -->
        <a class="navbar-brand " href="{{ url('/') }}">
          {{sysConfig('SITE_NAME')}}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{url('/')}}">首页<span class="sr-only">当前</span></a>
                </li>
                @foreach($cats as $cat)
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('category.show',$cat->slug)}}">{{$cat->name}}</a>
                    </li>
                @endforeach
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav navbar-right">
                @auth
                        @can('create', App\Models\Post::class)
                        <li class="nav-item d-none d-lg-block d-xl-block">
                          <a class="nav-link mt-1 mr-3 font-weight-bold" href="{{ route('post.create') }}">
                            <i class="fa fa-plus"></i>
                          </a>
                        </li>
                        @endcan
                        <li class="nav-item notification-badge d-none d-lg-block d-xl-block">
                            <a class="nav-link mr-3 badge badge-pill badge-{{ Auth::user()->notification_count > 0 ? 'hint' : 'secondary' }} text-white" href="{{ route('notifications.index') }}">
                                {{ Auth::user()->notification_count }}
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="userinfo" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                <span class="user-avatar pull-left" style="margin-right:8px; margin-top:-5px;">
                                    <img src="{{ Auth::user()->avatar }}" class="img-fluid rounded-circle" width="30px"
                                         height="30px">
                                </span>
                                {{ Auth::user()->name }}<span class="caret"></span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="userinfo">
                              @if(auth()->id() == 1)
                              <a href="{{ route('setting.index') }}" class="dropdown-item">
                                <i class="fa fa-cog fa-fw" aria-hidden="true"></i> 系统管理
                              </a>
                              <a href="{{ route('setting.clear') }}" class="dropdown-item">
                                <i class="fa fa-trash fa-fw" aria-hidden="true"></i> 清理缓存
                              </a>
                              @endif
                              <a href="{{ route('user.edit', auth()->user()->name) }}" class="dropdown-item">
                                  <i class="fa fa-pencil-square-o fa-fw" aria-hidden="true"></i> 编辑资料
                              </a>
                              <a href="{{ route('user.avatar', auth()->user()->name) }}" class="dropdown-item">
                                <i class="fa fa-picture-o fa-fw" aria-hidden="true"></i> 更换头像
                              </a>
                              <a href="{{ route('user.password', auth()->user()->name) }}" class="dropdown-item">
                                <i class="fa fa-lock fa-fw" aria-hidden="true"></i> 修改密码
                              </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" id="logout" href="#">
                                  <form action="{{ route('logout') }}" method="POST">
                                    {{ csrf_field() }}
                                    <button class="btn btn-block btn-default btn-sm" type="submit" name="button">退出</button>
                                  </form>
                                </a>
                            </div>
                        </li>
                @else
                    <li class="nav-item"><a class="nav-link" href="{{ route('login') }}">登录</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ route('register') }}">注册</a></li>
                @endauth
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/_paginate.blade.php
{{$posts->links()}}

resources/views/layouts/_post.blade.php
@foreach($posts as $post)
  <article class="post">
    <div class="post-head">
      <h3 class="post-title">
        <a href="{{route('post.show',$post->slug)}}">{{$post->title}}</a>
      </h3>
      <div class="post-meta">
          <span class="author">By
             <a href="{{route('user.show',$post->user->name)}}" data-toggle="tooltip" data-placement="bottom"
                title="查看{{$post->user->name}}发布的所有文章">{{$post->user->name}}
             </a>
          </span> &bull;
        <span class="date" data-toggle="tooltip" data-placement="bottom"
              title="{{ $post->created_at->toDateTimeString() }}">
            {{$post->created_at->diffForHumans() }}
          </span>&bull;
        <span class="comment-count" data-toggle="tooltip" data-placement="bottom" title="查看该文章的评论">
              <a href="{{route('post.show',$post->slug)}}#comments">{{$post->comments_count}}条评论</a>
          </span>
      </div>
    </div>
    @if($post->cover)
      <div class="featured-media">
        <a href="{{route('post.show',$post->slug)}}"><img src="{{$post->cover}}" alt="{{$post->title}}"></a>
      </div>
    @endif
    <div class="post-content">
      <p>{{$post->description}}</p>
    </div>
    <div class="post-footer">
      <div class="tag-list">
        <i class="fa fa-tag"></i>
        @foreach($post->tags as $tag)
          @if ($loop->last)
            <a href="{{route('tag.show',$tag->name)}}">{{$tag->name}}</a>
          @else
            <a href="{{route('tag.show',$tag->name)}}">{{$tag->name}}</a>,
          @endif
        @endforeach
      </div>
      <div class="statistical">
        <div data-toggle="tooltip" data-placement="top" title="这篇文章被查看了{{$post->visits()->count()}}次">
          <i class="fa fa-eye" aria-hidden="true"></i>
          <span class="badge">{{$post->visits()->count()}}</span>
        </div>
        <div data-toggle="tooltip" data-placement="top" title="{{$post->comments_count}}人评论了这篇文章">
          <i class="fa fa-comments" aria-hidden="true"></i>
          <span class="badge">{{$post->comments_count}}</span>
        </div>
        <div data-toggle="tooltip" data-placement="top" title="{{$post->favorites_count}}人赞了这篇文章">
          <i class="fa fa-heart" aria-hidden="true"></i>
          <span class="badge">{{$post->favorites_count}}</span>
        </div>
      </div>
    </div>
  </article>
@endforeach

resources/views/layouts/_sidebar.blade.php
<aside class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4 sidebar">
  <!-- start widget -->
  <div class="widget">
    <h4 class="title">搜索文章</h4>
    <div class="content">
      <input type="text" class="form-control" id="keyword" placeholder="请输入关键词...">
        <i id="search" class="fa fa-search float-right" aria-hidden="true"></i>
      </input>
    </div>
  </div>
  <!-- end widget -->

  <!-- start Newsletter widget -->
  <div class="widget">
    <h4 class="title">订阅邮件</h4>
    <div class="content newsletter">
      <div class="form-group">
        <div class="input-group">
          <input id="subscribe_email" class="form-control required email" type="email" name="email" required
                 placeholder="请输入您的电子邮件地址..."/>
        </div>
        <div class="input-group">
          <button class="btn btn-default btn-block" type="button" onclick="app.subscribe()">
            <span>订阅</span>
          </button>
        </div>
      </div>
    </div>
  </div>
  <!-- end Newsletter widget -->

  <!-- start Recent Post widget -->
  <div class="widget">
    <h4 class="title">最新发布</h4>
    <div class="content recent-post">
      @foreach($recent_posts as $post)
        <div class="recent-single-post">
          <a href="{{route('post.show',$post->slug)}}" class="post-title">{{$post->title}}</a>
          <div class="date">{{$post->created_at->toDateTimeString()}}</div>
        </div>
      @endforeach
    </div>
  </div>
  <!-- end Recent Post widget -->

  <!-- start tag cloud widget -->
  <div class="widget">
    <h4 class="title">标签云</h4>
    <div class="content tag-cloud">
      @foreach($top_tags as $tag)
        <a href="{{route('tag.show',$tag->name)}}">{{$tag->name}}</a>
      @endforeach
      <a href="{{route('tags')}}">...</a>
    </div>
  </div>
  <!-- end tag cloud widget -->

</aside>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="keyword" content="@yield('keyword', sysConfig('SITE_KEYWORD'))"/>
  <meta name="description" content="@yield('description', sysConfig('SITE_DESCRIPTION'))"/>
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <meta name="author" content="Flex">
  <link rel="manifest" href="/manifest.json">
  <!-- Styles -->
  <link href="{{ mix('css/app.css') }}" rel="stylesheet">
  @yield('styles')
  <title>@yield('title',sysConfig('SITE_NAME').' - '.sysConfig('SITE_SLOGAN'))</title>
</head>

@include('layouts._js')

<body class="{{ route_class() }}-page">

@section('body')

@show

</body>
<!-- Scripts -->
<script src="{{ mix('js/app.js') }}"></script>
@yield('scripts')
{!! sysConfig('STAT_CODE') !!}
</html>